# Generated by Django 6.0.3 on 2026-03-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snippet",
            old_name="highlight",
            new_name="highlighted",
        ),
    ]
